[package]
name = "discord-proposals"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18.2", features = ["full"] }
serenity = "0.11"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
